// Copyright 2021-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= VK_EXT_query_buffer
:toc: left
:refpage: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/
:sectnums:

This document outlines a proposal to make the management of query pool memory more explicit, allowing intermediate query results to be present in buffer memory, allowing the data and memory to be managed alongside other buffer objects.

///
VkDeviceAddress queryAddress
or
VkBuffer queryBuffer, VkDeviceSize queryBufferOffset
///

///
Is VK_ACCESS_2_QUERY_BUFFER_READ_BIT_EXT needed for vkCmdCopyQueryBufferResultsEXT? Is a pipeline stage needed?
Sould the implicit synchronization of the query commands be removed / made explicit?
Diffrent query kinds need diffrent barriers.
Could VkDependencyInfo or VkMemoryBarrier2 be extended to use a VkQueryLayout for this?
Should extra args be added for more control of the internal PipelineBarrier?
Can VK_QUERY_RESULT_WAIT_BIT be deprecated by using explicit synchronization instead?
///

///
From the vulkan spec:
    "vkCmdCopyQueryPoolResults is guaranteed to see the effect of
    previous uses of vkCmdResetQueryPool in the same queue, without any
    additional synchronization."
Can this guarantee be relaxed to remove a excess flushes?
///

[source,c]
----
VkResult vkCreateQueryLayoutEXT(
    VkDevice                                    device,
    const VkQueryPoolCreateInfo*                pCreateInfo,
    const VkAllocationCallbacks*                pAllocator,
    VkQueryLayout*                              pLayout);

void vkDestroyQueryLayoutEXT(
    VkDevice                                    device,
    VkQueryLayout                               layout,
    const VkAllocationCallbacks*                pAllocator);

void vkCmdResetQueryBufferEXT(
    VkCommandBuffer                             commandBuffer,
    VkQueryLayout                               layout,
    VkDeviceAddress                             queryAddress,
    uint32_t                                    queryCount);

// Provided by VK_EXT_host_query_reset
void vkResetQueryBufferEXT(
    VkDevice                                    device,
    VkQueryLayout                               layout,
    void*                                       pQueryData,
    uint32_t                                    queryCount);

void vkCmdBeginQueryBufferEXT(
    VkCommandBuffer                             commandBuffer,
    VkQueryLayout                               layout,
    VkDeviceAddress                             queryAddress,
    VkQueryControlFlags                         flags);

// Provided by VK_EXT_transform_feedback
void vkCmdBeginQueryBufferIndexedEXT(
    VkCommandBuffer                             commandBuffer,
    VkQueryLayout                               layout,
    VkDeviceAddress                             queryAddress,
    VkQueryControlFlags                         flags,
    uint32_t                                    index);

void vkCmdEndQueryBufferEXT(
    VkCommandBuffer                             commandBuffer,
    VkQueryLayout                               layout,
    VkDeviceAddress                             queryAddress);

// Provided by VK_EXT_transform_feedback
void vkCmdEndQueryBufferIndexedEXT(
    VkCommandBuffer                             commandBuffer,
    VkQueryLayout                               layout,
    VkDeviceAddress                             queryAddress,
    uint32_t                                    index);

VkResult vkGetQueryBufferResultsEXT(
    VkDevice                                    device,
    VkQueryLayout                               layout,
    const void*                                 pQueryData,
    uint32_t                                    queryCount,
    size_t                                      dataSize,
    void*                                       pData,
    VkDeviceSize                                stride,
    VkQueryResultFlags                          flags);

void vkCmdCopyQueryBufferResultsEXT(
    VkCommandBuffer                             commandBuffer,
    VkQueryLayout                               layout,
    VkDeviceAddress                             queryAddress,
    uint32_t                                    queryCount,
    VkBuffer                                    dstBuffer,
    VkDeviceSize                                dstOffset,
    VkDeviceSize                                stride,
    VkQueryResultFlags                          flags);

void vkCmdWriteTimestampBufferEXT(
    VkCommandBuffer                             commandBuffer,
    VkPipelineStageFlags2                       stage,
    VkQueryLayout                               layout,
    VkDeviceAddress                             queryAddress);


static const VkBufferUsageFlagBits VK_BUFFER_USAGE_QUERY_BUFFER_BIT_EXT = 0x08000000;

static const VkAccessFlagBits2 VK_ACCESS_2_QUERY_BUFFER_READ_BIT_EXT = 0x1000000000000ULL;
static const VkAccessFlagBits2 VK_ACCESS_2_QUERY_BUFFER_WRITE_BIT_EXT = 0x2000000000000ULL;
----

